env:
  mode: "development"

database:
  path: "runtime/main.db"

storage:
  assets-path: "runtime/storage/assets"
  contents-path: "runtime/storage/contents"

server:
  port: "8080"
  session-store:
    private-key: ""
